In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Python/Dataset/Used_Bikes.csv')
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [ ]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [ ]:
new_df=df.drop(['bike_name','city'], axis='columns')
new_df

          price  kms_driven        owner   age  power          brand
0       35000.0     17654.0  First Owner   3.0  110.0            TVS
1      119900.0     11000.0  First Owner   4.0  350.0  Royal Enfield
2      600000.0       110.0  First Owner   8.0  675.0        Triumph
3       65000.0     16329.0  First Owner   4.0  180.0            TVS
4       80000.0     10000.0  First Owner   3.0  150.0         Yamaha
...         ...         ...          ...   ...    ...            ...
32643   39000.0     22000.0  First Owner   4.0  100.0           Hero
32644   30000.0      6639.0  First Owner   9.0  180.0            TVS
32645   60000.0     20373.0  First Owner   6.0  220.0          Bajaj
32646   15600.0     84186.0  First Owner  16.0  125.0           Hero
32647   22000.0     60857.0  First Owner  13.0  150.0          Bajaj

[32648 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
new_df['owner']=le.fit_transform(new_df['owner'])

In [ ]:
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(class_mapping)

{'First Owner': 0, 'Fourth Owner Or More': 1, 'Second Owner': 2, 'Third Owner': 3}

In [ ]:
new_df['brand']=le.fit_transform(new_df['brand'])

In [ ]:
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(class_mapping)

{'BMW': 0, 'Bajaj': 1, 'Benelli': 2, 'Ducati': 3, 'Harley-Davidson': 4, 'Hero': 5, 'Honda': 6, 'Hyosung': 7, 'Ideal': 8, 'Indian': 9, 'Jawa': 10, 'KTM': 11, 'Kawasaki': 12, 'LML': 13, 'MV': 14, 'Mahindra': 15, 'Rajdoot': 16, 'Royal Enfield': 17, 'Suzuki': 18, 'TVS': 19, 'Triumph': 20, 'Yamaha': 21, 'Yezdi': 22}

In [ ]:
new_df

          price  kms_driven  owner   age  power  brand
0       35000.0     17654.0      0   3.0  110.0     19
1      119900.0     11000.0      0   4.0  350.0     17
2      600000.0       110.0      0   8.0  675.0     20
3       65000.0     16329.0      0   4.0  180.0     19
4       80000.0     10000.0      0   3.0  150.0     21
...         ...         ...    ...   ...    ...    ...
32643   39000.0     22000.0      0   4.0  100.0      5
32644   30000.0      6639.0      0   9.0  180.0     19
32645   60000.0     20373.0      0   6.0  220.0      1
32646   15600.0     84186.0      0  16.0  125.0      5
32647   22000.0     60857.0      0  13.0  150.0      1

[32648 rows x 6 columns]

In [ ]:
new_df.tail()

         price  kms_driven  owner   age  power  brand
32643  39000.0     22000.0      0   4.0  100.0      5
32644  30000.0      6639.0      0   9.0  180.0     19
32645  60000.0     20373.0      0   6.0  220.0      1
32646  15600.0     84186.0      0  16.0  125.0      5
32647  22000.0     60857.0      0  13.0  150.0      1

In [ ]:
x=new_df.drop('price',axis='columns')
y=new_df['price']

In [ ]:
new_df.isna().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [ ]:
print(type(x_train))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(type(x_test))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
model=SVR()
model.fit(x_train,y_train)

SVR()

In [ ]:
x_train

       kms_driven  owner   age  power  brand
23583     84186.0      0  16.0  125.0      5
10212     34968.0      0  14.0  150.0      5
10013     22824.0      0   8.0  100.0      5
18785     13216.0      0   4.0  390.0     11
16937     52000.0      0  10.0  150.0     21
...           ...    ...   ...    ...    ...
3745      13500.0      0   5.0  350.0     17
8041      16476.0      0   5.0  350.0     17
21597     13216.0      0   4.0  390.0     11
18397     60857.0      0  13.0  150.0      1
13802     27000.0      0   9.0  150.0     21

[26118 rows x 5 columns]

In [ ]:
x_test

       kms_driven  owner   age  power  brand
30418     65000.0      0  12.0  150.0     21
26829     22000.0      0   4.0  100.0      5
28163      7127.0      0   5.0  220.0      1
25511     13216.0      0   4.0  390.0     11
26270     41939.0      0   8.0  200.0      1
...           ...    ...   ...    ...    ...
20360      3869.0      0  16.0  100.0      5
31887     60857.0      0  13.0  150.0      1
31797     20000.0      0   4.0  350.0     17
12535     48587.0      0   8.0  150.0      5
16223       140.0      0   3.0  160.0      6

[6530 rows x 5 columns]

In [ ]:
y_predicted=model.predict(x_test)

In [ ]:
model.score(x_test,y_test)

-0.057264650003585826

In [ ]:
y_predicted

array([39185.61828327, 44501.10627108, 46067.7417872 , ...,
       44816.1774356 , 40023.61596725, 46094.48890985])

In [ ]:
a=float(input('kms_driven: '))
print("'First Owner': 0, 'Fourth Owner Or More': 1, 'Second Owner': 2, 'Third Owner': 3'")
b=float(input('owner: '))
c=float(input('age: '))
d=float(input('power: '))
print("""'BMW': 0, 'Bajaj': 1, 'Benelli': 2, 'Ducati': 3, 'Harley-Davidson': 4, 'Hero': 5, 'Honda': 6,
 'Hyosung': 7, 'Ideal': 8, 'Indian': 9, 'Jawa': 10, 'KTM': 11, 'Kawasaki': 12, 'LML': 13, 'MV': 14, 'Mahindra': 15,
'Rajdoot': 16, 'Royal Enfield': 17, 'Suzuki': 18, 'TVS': 19, 'Triumph': 20, 'Yamaha': 21, 'Yezdi': 22""")
e=float(input('brand: '))
df=pd.DataFrame([[a],[b],[c],[d],[e]], dtype=int)
y_predicted=model.predict([[a,b,c,d,e]])
print('the price is: ',y_predicted)

kms_driven: 11000
'First Owner': 0, 'Fourth Owner Or More': 1, 'Second Owner': 2, 'Third Owner': 3'
owner: 0
age: 4
power: 350
'BMW': 0, 'Bajaj': 1, 'Benelli': 2, 'Ducati': 3, 'Harley-Davidson': 4, 'Hero': 5, 'Honda': 6,
 'Hyosung': 7, 'Ideal': 8, 'Indian': 9, 'Jawa': 10, 'KTM': 11, 'Kawasaki': 12, 'LML': 13, 'MV': 14, 'Mahindra': 15,
'Rajdoot': 16, 'Royal Enfield': 17, 'Suzuki': 18, 'TVS': 19, 'Triumph': 20, 'Yamaha': 21, 'Yezdi': 22
brand: 17
the price is:  [45851.72423855]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(